### ISSUE TITLE
Not scrolling in safari mobile

### ISSUE THREAD

**Issue by Bernix01** [cbopp-art/lightcase#23] opened 2015-07-13 15:31 UTC
It works perfect in chrome mobile but in safari mobile it just won't let me scroll the iframe content... 
Pls help

**Comment by cbopp-art** [comment] 2015-07-13 18:18
@Bernix01
Hi!
Could you share some more details? I have no problems, neither on a mobile phone using safari.
Thanks!

**Comment by cbopp-art** [comment] 2015-08-15 19:26
@Bernix01
I close this issue cause I couldn't reproduce same issue by myself neither that I didn't got any feedback.
In case you still would have troubles with this, feel absolutely free to reopen this issue again.

Thanks!

**Closed by cbopp-art** 2015-08-15 19:26 UTC
