### ISSUE TITLE
While closing in midst of loading next image. Lightbox pops up again with the loaded image

### ISSUE THREAD

**Issue by MadhuNandi** [cbopp-art/lightcase#17] opened 2015-05-14 06:38 UTC
Here I'm facing a strange issue, if I am closing the lightbox slideshow when it's in mid of loading next image the lightbox closes right there and pops up again with the loaded image therefore continues slideshow as normal. 

Is anyone has encountered same issues.? If yes, Someone could help me in resolving this.

**Comment by cbopp-art** [comment] 2015-05-14 19:08
@MadhuNandi 
Thanks for reporting this bug. I could reproduce this bug and fixed it. I hope this does fix it also for you.

**Comment by MadhuNandi** [comment] 2015-05-15 06:10
@cbopp-art  Thanks for your quick reply. But still I'm facing same issue.

**Comment by cbopp-art** [comment] 2015-05-15 06:26
@MadhuNandi 
Hmm, are you using branch [v2.1.x](https://github.com/cbopp-art/lightcase/tree/v2.1.x)?
Could you provide me a link to an online demo?

Actually, [39e6d75](https://github.com/cbopp-art/lightcase/commit/39e6d75f9c8797934e9651390ea1be3a9b5dbad1) does stop the ongoing timeout now immediately after the close was introduced.

**Comment by MadhuNandi** [comment] 2015-05-15 07:13
http://madhunandi.vivyobeta.com/

Go to gallery and click 'Play Slideshow' button overthere. Close it in mid of loading next image.

**Comment by cbopp-art** [comment] 2015-05-15 07:24
I can't see that you're file ```lightcase.js``` has applied the following change [39e6d75](https://github.com/cbopp-art/lightcase/commit/39e6d75f9c8797934e9651390ea1be3a9b5dbad1)

**Comment by MadhuNandi** [comment] 2015-05-15 07:27
I had made those changes in my local file and has been tested. Still I faced issue. I had sent you an facebook request to you. could we continue our chat over there if it's fine with you.

**Comment by cbopp-art** [comment] 2015-05-21 09:40
How is your status here?

**Comment by cbopp-art** [comment] 2015-08-15 19:27
@MadhuNandi 
Hi Madhu, could I close this issue now?

**Comment by cbopp-art** [comment] 2015-09-29 07:14
@MadhuNandi I'm going to close this issue now because I didn't got any feedback. In case that this problem still would be existent, please just reopen a new one.

Thanks!

**Closed by cbopp-art** 2015-09-29 07:14 UTC
